name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - uses: nrwl/nx-set-shas@v4
        # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track master origin/master
      - run: npx nx affected -t=lint,test,build --base=master --head=HEAD
